spring:
  application:
    name: sales-system

  datasource:
    url: jdbc:mysql://localhost:3306/sales_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: SalesHikariCP

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: false
    open-in-view: false

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.example.sales_system: DEBUG

